/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface AddressRepository extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): AddressRepository;
  clone(): AddressRepository;
  methods: {
    getAddress(key: string | number[]): NonPayableTransactionObject<string>;

    getGameService(): NonPayableTransactionObject<string>;

    getGoldToken(): NonPayableTransactionObject<string>;

    getIronToken(): NonPayableTransactionObject<string>;

    getOilToken(): NonPayableTransactionObject<string>;

    getPlanetRepository(): NonPayableTransactionObject<string>;

    getStarshipRepository(): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    setGameService(_address: string): NonPayableTransactionObject<void>;

    setGoldToken(_address: string): NonPayableTransactionObject<void>;

    setIronToken(_address: string): NonPayableTransactionObject<void>;

    setOilToken(_address: string): NonPayableTransactionObject<void>;

    setPlanetRepository(_address: string): NonPayableTransactionObject<void>;

    setStarshipRepository(_address: string): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;
  };
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
