/*
 * Copyright (c) 2020. Space Traders
 * Authors: Mikael Lazarev, Ivan Fedorov
 */

/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface PlanetRepository extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): PlanetRepository;
  clone(): PlanetRepository;
  methods: {
    addPlanet(
      planet: string,
      name: string,
      x: number | string,
      y: number | string
    ): NonPayableTransactionObject<void>;

    getPlanet(
      planet: string
    ): NonPayableTransactionObject<{
      name: string;
      x: string;
      y: string;
      0: string;
      1: string;
      2: string;
    }>;

    getPlanetsLength(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
