/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AddressStorageInterface extends ethers.utils.Interface {
  functions: {
    "c_0xc99a04f0(bytes32)": FunctionFragment;
    "getAddress(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0xc99a04f0",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "c_0xc99a04f0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;

  events: {};
}

export class AddressStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AddressStorageInterface;

  functions: {
    c_0xc99a04f0(
      c__0xc99a04f0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0xc99a04f0(bytes32)"(
      c__0xc99a04f0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    getAddress(key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "getAddress(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  c_0xc99a04f0(
    c__0xc99a04f0: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0xc99a04f0(bytes32)"(
    c__0xc99a04f0: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  getAddress(key: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getAddress(bytes32)"(
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    c_0xc99a04f0(
      c__0xc99a04f0: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0xc99a04f0(bytes32)"(
      c__0xc99a04f0: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getAddress(key: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getAddress(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    c_0xc99a04f0(
      c__0xc99a04f0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0xc99a04f0(bytes32)"(
      c__0xc99a04f0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAddress(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getAddress(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0xc99a04f0(
      c__0xc99a04f0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0xc99a04f0(bytes32)"(
      c__0xc99a04f0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAddress(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddress(bytes32)"(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
