/*
 * Copyright (c) 2020. Space Traders
 * Authors: Mikael Lazarev, Ivan Fedorov
 */

/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AddressRepositoryContract } from "./AddressRepository";
import { AddressStorageContract } from "./AddressStorage";
import { BEP20TokenContract } from "./BEP20Token";
import { GameContract } from "./Game";
import { IBEP20Contract } from "./IBEP20";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";
import { PlanetRepositoryContract } from "./PlanetRepository";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AddressRepository"): AddressRepositoryContract;
      require(name: "AddressStorage"): AddressStorageContract;
      require(name: "BEP20Token"): BEP20TokenContract;
      require(name: "Game"): GameContract;
      require(name: "IBEP20"): IBEP20Contract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "PlanetRepository"): PlanetRepositoryContract;
    }
  }
}

export {
  AddressRepositoryContract,
  AddressRepositoryInstance,
} from "./AddressRepository";
export {
  AddressStorageContract,
  AddressStorageInstance,
} from "./AddressStorage";
export { BEP20TokenContract, BEP20TokenInstance } from "./BEP20Token";
export { GameContract, GameInstance } from "./Game";
export { IBEP20Contract, IBEP20Instance } from "./IBEP20";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
export {
  PlanetRepositoryContract,
  PlanetRepositoryInstance,
} from "./PlanetRepository";
